//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by Ctrl+C the XML and Edit->Paste Special->XML as classes
//   make sure all int fields in the XML are set to 2147483647 (max value)
//   That's right, find duration_ts in the XML and set its value to 2147483647
//   Otherwise they will be made to smallest type - byte
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace Vidka.Core.VideoMeta {



	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
	public partial class ffprobe
	{

		private ffprobeStream[] streamsField;

		private ffprobeFormat formatField;

		/// <remarks/>
		[System.Xml.Serialization.XmlArrayItemAttribute("stream", IsNullable = false)]
		public ffprobeStream[] streams
		{
			get
			{
				return this.streamsField;
			}
			set
			{
				this.streamsField = value;
			}
		}

		/// <remarks/>
		public ffprobeFormat format
		{
			get
			{
				return this.formatField;
			}
			set
			{
				this.formatField = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ffprobeStream
	{

		private string codec_typeField;

		private string r_frame_rateField;

		private string avg_frame_rateField;

		private uint duration_tsField;

		private bool duration_tsFieldSpecified;

		private decimal durationField;

		private bool durationFieldSpecified;

		private uint nb_framesField;

		private bool nb_framesFieldSpecified;

		private uint nb_read_framesField;

		private bool nb_read_framesFieldSpecified;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string codec_type
		{
			get
			{
				return this.codec_typeField;
			}
			set
			{
				this.codec_typeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string r_frame_rate
		{
			get
			{
				return this.r_frame_rateField;
			}
			set
			{
				this.r_frame_rateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string avg_frame_rate
		{
			get
			{
				return this.avg_frame_rateField;
			}
			set
			{
				this.avg_frame_rateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint duration_ts
		{
			get
			{
				return this.duration_tsField;
			}
			set
			{
				this.duration_tsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool duration_tsSpecified
		{
			get
			{
				return this.duration_tsFieldSpecified;
			}
			set
			{
				this.duration_tsFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal duration
		{
			get
			{
				return this.durationField;
			}
			set
			{
				this.durationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool durationSpecified
		{
			get
			{
				return this.durationFieldSpecified;
			}
			set
			{
				this.durationFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint nb_frames
		{
			get
			{
				return this.nb_framesField;
			}
			set
			{
				this.nb_framesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool nb_framesSpecified
		{
			get
			{
				return this.nb_framesFieldSpecified;
			}
			set
			{
				this.nb_framesFieldSpecified = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint nb_read_frames
		{
			get
			{
				return this.nb_read_framesField;
			}
			set
			{
				this.nb_read_framesField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlIgnoreAttribute()]
		public bool nb_read_framesSpecified
		{
			get
			{
				return this.nb_read_framesFieldSpecified;
			}
			set
			{
				this.nb_read_framesFieldSpecified = value;
			}
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
	public partial class ffprobeFormat
	{

		private string filenameField;

		private byte nb_streamsField;

		private byte nb_programsField;

		private string format_nameField;

		private string format_long_nameField;

		private decimal start_timeField;

		private decimal durationField;

		private uint sizeField;

		private uint bit_rateField;

		private byte probe_scoreField;

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string filename
		{
			get
			{
				return this.filenameField;
			}
			set
			{
				this.filenameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public byte nb_streams
		{
			get
			{
				return this.nb_streamsField;
			}
			set
			{
				this.nb_streamsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public byte nb_programs
		{
			get
			{
				return this.nb_programsField;
			}
			set
			{
				this.nb_programsField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string format_name
		{
			get
			{
				return this.format_nameField;
			}
			set
			{
				this.format_nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string format_long_name
		{
			get
			{
				return this.format_long_nameField;
			}
			set
			{
				this.format_long_nameField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal start_time
		{
			get
			{
				return this.start_timeField;
			}
			set
			{
				this.start_timeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public decimal duration
		{
			get
			{
				return this.durationField;
			}
			set
			{
				this.durationField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint size
		{
			get
			{
				return this.sizeField;
			}
			set
			{
				this.sizeField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public uint bit_rate
		{
			get
			{
				return this.bit_rateField;
			}
			set
			{
				this.bit_rateField = value;
			}
		}

		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public byte probe_score
		{
			get
			{
				return this.probe_scoreField;
			}
			set
			{
				this.probe_scoreField = value;
			}
		}
	}


	

}